version: 2
jobs:
    bill-service:
        working_directory: ~/soa2019_group7/bill_service/
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            MAVEN_OPTS: -Xmx3200m

        steps:

            - checkout:
                path: ~/soa2019_group7
            - setup_remote_docker:
                docker_layer_caching: true
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "pom.xml" }}
                    - v1-dependencies-
            - run:
                name: Build Docker Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docker build -t $DOCKER_USERNAME/bill_service .
                    docker push $DOCKER_USERNAME/bill_service
            - save_cache:
                key: v1-dependencies-{{ checksum "pom.xml" }}
                paths:
                    - ~/.m2
            - run:
                name: run test
                command: |
                    mvnw test

workflows:
    version: 2
    complie:
        jobs:
            - bill-service:
                filters:
                    branches:
                        only:
                            - master
