version: 2
jobs:
  build-bill:
    working_directory: ~/soa2019_group7/bill_service/
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/bill:$CIRCLE_BUILD_NUM

  build-report:
    working_directory: ~/soa2019_group7/report_service
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/soa2019_group7
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: Auth to gcloud
          command: |
            echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${PROJECT_ID}
            gcloud auth configure-docker
      - run :
          name: Build and push docker images
          command: |
            docker build -t asia.gcr.io/soa-group-7-174/report:$CIRCLE_BUILD_NUM .
            docker push asia.gcr.io/soa-group-7-174/report:$CIRCLE_BUILD_NUM
workflows:
  version: 2
  workflow:
    jobs:
    - build-bill
    - build-report
